/*============================================================================
  Business Metrics (Executive-ready KPIs with explicit assumptions)

  Principles:
  - Do NOT fabricate ROI. Use observed costs/downtime from MAINTENANCE_HISTORY.
  - Where counterfactual is required (e.g., "avoided downtime"), use an explicit
    assumptions table so exec metrics are transparent and editable.
============================================================================*/

USE ROLE SF_INTELLIGENCE_DEMO;

USE DATABASE PREDICTIVE_MAINTENANCE;
USE SCHEMA OPERATIONS;

CREATE OR REPLACE TABLE OPERATIONS.DEMO_ASSUMPTIONS (
  ASSUMPTION_KEY STRING,
  ASSUMPTION_VALUE FLOAT,
  UNIT STRING,
  DESCRIPTION STRING,
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Seed defaults (idempotent)
MERGE INTO OPERATIONS.DEMO_ASSUMPTIONS t
USING (
  SELECT * FROM VALUES
    ('AD_REVENUE_PER_DOWNTIME_HOUR_USD', 120.0, 'USD/hour', 'Estimated advertising revenue impact per hour of screen downtime (edit for your customer).'),
    ('EST_DOWNTIME_HOURS_AVOIDED_PER_REMOTE_SUCCESS', 4.0, 'hours', 'Estimated downtime avoided when a remote remediation succeeds before a full outage.'),
    ('EST_FIELD_DISPATCH_COST_USD', 500.0, 'USD', 'Estimated cost per physical field dispatch (labor+travel baseline).')
  AS s(ASSUMPTION_KEY, ASSUMPTION_VALUE, UNIT, DESCRIPTION)
) s
ON t.ASSUMPTION_KEY = s.ASSUMPTION_KEY
WHEN MATCHED THEN UPDATE SET
  ASSUMPTION_VALUE = t.ASSUMPTION_VALUE
WHEN NOT MATCHED THEN INSERT (ASSUMPTION_KEY, ASSUMPTION_VALUE, UNIT, DESCRIPTION)
VALUES (s.ASSUMPTION_KEY, s.ASSUMPTION_VALUE, s.UNIT, s.DESCRIPTION);

USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW ANALYTICS.V_EXEC_KPIS AS
WITH a AS (
  SELECT
    MAX(IFF(ASSUMPTION_KEY = 'AD_REVENUE_PER_DOWNTIME_HOUR_USD', ASSUMPTION_VALUE, NULL)) AS AD_REV_PER_HR,
    MAX(IFF(ASSUMPTION_KEY = 'EST_DOWNTIME_HOURS_AVOIDED_PER_REMOTE_SUCCESS', ASSUMPTION_VALUE, NULL)) AS DT_AVOID_PER_REMOTE,
    MAX(IFF(ASSUMPTION_KEY = 'EST_FIELD_DISPATCH_COST_USD', ASSUMPTION_VALUE, NULL)) AS FIELD_DISPATCH_COST
  FROM PREDICTIVE_MAINTENANCE.OPERATIONS.DEMO_ASSUMPTIONS
),
fleet AS (
  SELECT
    COUNT(*) AS FLEET_SIZE,
    SUM(IFF(OVERALL_STATUS = 'CRITICAL', 1, 0)) AS CRITICAL_NOW,
    SUM(IFF(OVERALL_STATUS = 'WARNING', 1, 0)) AS WARNING_NOW
  FROM PREDICTIVE_MAINTENANCE.ANALYTICS.V_FLEET_DEVICE_STATUS
),
watch AS (
  SELECT COUNT(*) AS WATCHLIST_COUNT
  FROM PREDICTIVE_MAINTENANCE.OPERATIONS.WATCHLIST_CURRENT
),
pred AS (
  SELECT COUNT(*) AS PREDICTED_FAILURES_48H
  FROM PREDICTIVE_MAINTENANCE.ANALYTICS.V_FAILURE_PREDICTIONS_CURRENT
  WHERE HORIZON_HOURS = 48
),
wo AS (
  SELECT
    COUNT(*) AS OPEN_WORK_ORDERS,
    SUM(IFF(RECOMMENDED_CHANNEL = 'FIELD', 1, 0)) AS FIELD_RECOMMENDED,
    SUM(IFF(RECOMMENDED_CHANNEL = 'REMOTE', 1, 0)) AS REMOTE_RECOMMENDED
  FROM PREDICTIVE_MAINTENANCE.ANALYTICS.V_WORK_ORDERS_CURRENT
),
hist30 AS (
  SELECT
    COUNT(*) AS INCIDENTS_30D,
    SUM(DOWNTIME_HOURS) AS DOWNTIME_HOURS_30D,
    SUM(REVENUE_IMPACT_USD) AS REVENUE_IMPACT_USD_30D,
    SUM(IFF(RESOLUTION_TYPE IN ('Field Service','Part Replacement'), 1, 0)) AS FIELD_EVENTS_30D,
    SUM(IFF(RESOLUTION_TYPE = 'Remote Fix', 1, 0)) AS REMOTE_EVENTS_30D,
    AVG(IFF(RESOLUTION_TYPE IN ('Field Service','Part Replacement'), TOTAL_COST_USD, NULL)) AS AVG_FIELD_EVENT_COST_USD,
    AVG(IFF(RESOLUTION_TYPE = 'Remote Fix', TOTAL_COST_USD, NULL)) AS AVG_REMOTE_EVENT_COST_USD
  FROM PREDICTIVE_MAINTENANCE.RAW_DATA.MAINTENANCE_HISTORY
  WHERE INCIDENT_DATE >= DATEADD('day', -30, (SELECT DEMO_AS_OF_TS FROM PREDICTIVE_MAINTENANCE.OPERATIONS.V_DEMO_TIME))
    AND INCIDENT_DATE < (SELECT DEMO_AS_OF_TS FROM PREDICTIVE_MAINTENANCE.OPERATIONS.V_DEMO_TIME)
),
remote_exec30 AS (
  SELECT
    COUNT(*) AS REMOTE_EXECUTIONS_30D,
    SUM(IFF(STATUS = 'SUCCESS', 1, 0)) AS REMOTE_SUCCESSES_30D,
    SUM(IFF(STATUS = 'ESCALATED', 1, 0)) AS REMOTE_ESCALATIONS_30D
  FROM PREDICTIVE_MAINTENANCE.OPERATIONS.REMOTE_EXECUTIONS
  WHERE STARTED_AT >= DATEADD('day', -30, (SELECT DEMO_AS_OF_TS FROM PREDICTIVE_MAINTENANCE.OPERATIONS.V_DEMO_TIME))
    AND STARTED_AT < (SELECT DEMO_AS_OF_TS FROM PREDICTIVE_MAINTENANCE.OPERATIONS.V_DEMO_TIME)
)
SELECT
  (SELECT DEMO_AS_OF_TS FROM PREDICTIVE_MAINTENANCE.OPERATIONS.V_DEMO_TIME) AS AS_OF_TS,

  -- Fleet health
  fleet.FLEET_SIZE,
  fleet.CRITICAL_NOW,
  fleet.WARNING_NOW,
  watch.WATCHLIST_COUNT,
  pred.PREDICTED_FAILURES_48H,
  wo.OPEN_WORK_ORDERS,

  -- Operational workload / outcomes (observed)
  hist30.INCIDENTS_30D,
  hist30.FIELD_EVENTS_30D,
  hist30.REMOTE_EVENTS_30D,
  hist30.DOWNTIME_HOURS_30D,
  hist30.REVENUE_IMPACT_USD_30D,
  hist30.AVG_FIELD_EVENT_COST_USD,
  hist30.AVG_REMOTE_EVENT_COST_USD,

  -- Remote automation outcomes (simulated executions)
  remote_exec30.REMOTE_EXECUTIONS_30D,
  remote_exec30.REMOTE_SUCCESSES_30D,
  remote_exec30.REMOTE_ESCALATIONS_30D,
  IFF(remote_exec30.REMOTE_EXECUTIONS_30D = 0, NULL, remote_exec30.REMOTE_SUCCESSES_30D / remote_exec30.REMOTE_EXECUTIONS_30D) AS REMOTE_EXEC_SUCCESS_RATE_30D,

  -- Transparent estimates (assumption-driven)
  a.AD_REV_PER_HR AS ASSUMP_AD_REVENUE_PER_DOWNTIME_HOUR_USD,
  a.DT_AVOID_PER_REMOTE AS ASSUMP_DOWNTIME_HOURS_AVOIDED_PER_REMOTE_SUCCESS,
  a.FIELD_DISPATCH_COST AS ASSUMP_FIELD_DISPATCH_COST_USD,

  (remote_exec30.REMOTE_SUCCESSES_30D * a.DT_AVOID_PER_REMOTE) AS EST_DOWNTIME_HOURS_AVOIDED_30D,
  (remote_exec30.REMOTE_SUCCESSES_30D * a.DT_AVOID_PER_REMOTE * a.AD_REV_PER_HR) AS EST_REVENUE_PROTECTED_USD_30D,
  (remote_exec30.REMOTE_SUCCESSES_30D * a.FIELD_DISPATCH_COST) AS EST_FIELD_COST_AVOIDED_USD_30D
FROM a, fleet, watch, pred, wo, hist30, remote_exec30;

SELECT * FROM ANALYTICS.V_EXEC_KPIS;


